name: Portfolio
on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          cache: 'yarn'

      - name: Setup Pages
        uses: actions/configure-pages@v3
        with: 
          static_site_generator: next

      - name: Install dependencies
        run: yarn install && yarn build

      - name: Build
        run: yarn export

